name: mental_test_quiz
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^4.0.1
  facebook_audience_network: ^0.8.0
  launch_review: ^1.0.1
  url_launcher: ^5.4.2
   # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  sqflite: any
  path_provider: any
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - assets/schizophrenia.json
     - assets/anxiety.json
     - assets/depression.json
     - assets/ocd.json
     - assets/did.json
     - assets/agoraphobia.json
     - assets/ptsd.json
     - assets/aspd.json
     - assets/autism.json
     - assets/domestic.json
     - assets/bed.json
     - assets/bipolar.json
     - assets/borderline.json
     - assets/childaut.json
     - assets/asperger.json
     - assets/grief.json
     - assets/dementia.json
     - assets/internet.json
     - assets/narcissistic.json
     - assets/paranoid.json
     - assets/psychosis.json
     - assets/psychopathy.json
     - assets/relationship.json
     - assets/separation.json
     - assets/sex.json
     - assets/social.json
     - assets/game.json
     - assets/mania.json
     - assets/panic.json
     - assets/repetitive.json
     - assets/images/borderline.png
     - assets/images/schizophrenia.jpg
     - assets/images/aspd.jpg
     - assets/images/applogo.jpg
     - assets/images/anxiety.jpg
     - assets/images/autism.jpg
     - assets/images/eating.jpg
     - assets/images/bipolar.jpg
     - assets/images/childaut.jpg
     - assets/images/asperger.jpg
     - assets/images/dementia.jpg
     - assets/images/grief.jpg
     - assets/images/depression.jpg
     - assets/images/did.jpg
     - assets/images/domestic.jpg
     - assets/images/internet.jpg
     - assets/images/narcissistic.jpg
     - assets/images/paranoid.jpg
     - assets/images/ptsd.jpg
     - assets/images/psychopathy.jpg
     - assets/images/psychosis.jpg
     - assets/images/relationship.jpg
     - assets/images/separation.jpg
     - assets/images/sex.jpg
     - assets/images/social.jpg
     - assets/images/game.jpg
     - assets/images/mania.jpg
     - assets/images/ocd.jpg
     - assets/images/panic.jpg
     - assets/images/agoraphobia.jpg
     - assets/images/repetitive.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
